language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libapache2-mod-php5 php5-mysql subversion
 - svn co https://forge.indepnet.net/svn/glpi/branches/0.84-bugfixes glpi
 - sudo mv glpi /var/www/fusion0.84
 - mysql -e "CREATE DATABASE glpi;"
 - mysql -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis')";
 - sudo echo '<?php class DB extends DBmysql {var $dbhost = "localhost";var $dbuser = "travis";var $dbpassword= "travis";var $dbdefault = "glpi";}' > /var/www/fusion0.84/config/config_db.php
 - cat /var/www/fusion0.84/install/mysql/glpi-0.84.1-empty.sql | mysql -utravis -ptravis glpi
 - sudo mkdir /var/www/fusion0.84/plugins/fusioninventory
 - sudo cp -r . /var/www/fusion0.84/plugins/fusioninventory
 - sudo chown -R travis:www-data /var/www/fusion0.84
 - sudo chmod -R g+w /var/www/fusion0.84
 - cd /var/www/fusion0.84/plugins/fusioninventory/tools
 - php cli_install.php
 - cd /var/www/fusion0.84/plugins/fusioninventory/phpunit/
 - echo > /var/www/fusion0.84/files/_log/php-errors.log

script: phpunit AllTests.php && test -f result.stamp
