language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libapache2-mod-php5 php5-mysql
 - wget -O glpi.tar.gz https://forge.indepnet.net/attachments/download/1593/glpi-0.84.2.tar.gz
 - tar xf glpi.tar.gz
 - sudo mv glpi /var/www/fusion0.84
 - mysql -e 'create database glpi;'
 - sudo echo '<?php class DB extends DBmysql {var $dbhost = "localhost";var $dbuser = "travis";var $dbpassword= "travis";var $dbdefault = "glpi";}' > /var/www/fusion0.84/config/config_db.php
 - mysql -e 'create database glpi;'
 - cat /var/www/fusion0.84/install/mysql/glpi-0.83.1-empty.sql | mysql -utravis glpi
 - sudo mkdir /var/www/fusion0.84/plugins/fusioninventory
 - sudo cp -r . /var/www/fusion0.84/plugins/fusioninventory
 - cd /var/www/fusion0.84/plugins/fusioninventory/phpunit/

script: phpunit AllTests.php
